class BoilerDefaults:
	MIN_TEMP = 20.0
	MAX_TEMP = 85.0
	DEFAULT_TEMP = 40.0
	HYSTERESIS = 5.0
	MIN_ON_TIME = 60
	MIN_OFF_TIME = 60
	MODE_RELAY = 'relay'
	MODE_SENSOR = 'sensor'
	DEFAULT_MODE = MODE_RELAY
	WATCHDOG_TIMEOUT = 3600
	MAX_TEMP_AGE = 300
	SAFETY_MARGIN = 2.0
	STATUS_INTERVAL = 300
	MAX_RETRIES = 3

class ErrorCodes:
	TEMP_READ_FAIL = 'E001'
	TEMP_TOO_HIGH = 'E002'
	TEMP_TOO_LOW = 'E003'
	TEMP_SENSOR_TIMEOUT = 'E004'
	COMM_TIMEOUT = 'E101'
	LORA_INIT_FAIL = 'E102'
	LORA_SEND_FAIL = 'E103'
	CONTROL_TIMEOUT = 'E201'
	RELAY_FAIL = 'E202'
	SENSOR_FAIL = 'E203'
	DISPLAY_FAIL = 'E301'
	MODULE_MISSING = 'E302'
	CONFIG_ERROR = 'E303'

class SystemParameters:
	DISPLAY_SLOT = 2
	IO_MODULE_SLOT = 6
	SSR_MODULE_SLOT = 5
	MAX_ERROR_LOG = 50
	MAX_TEMP_HISTORY = 60
	DISPLAY_UPDATE_INTERVAL = 1.0
	MAX_MESSAGE_LENGTH = 21
	CONTROL_INTERVAL = 1.0
	TREND_WINDOW = 300
	CONFIG_FILE = 'boiler_config.json'
	ERROR_LOG_FILE = 'error_log.json'
	BACKUP_CONFIG = 'boiler_config.backup.json'

class MessageTypes:
	STATUS = 0
	CONFIG = 1
	COMMAND = 2
	QUERY = 3
	DIAGNOSTIC = 4
	ERROR = 5
	CMD_RESET = 0
	CMD_DIAGNOSTIC = 1
	CMD_CLEAR_ERRORS = 2
	QUERY_STATUS = 0
	QUERY_DIAGNOSTIC = 1
	QUERY_ERRORS = 2
	STATUS_MODE = 0
	STATUS_TEMP = 1
	STATUS_SETPOINT = 2
	STATUS_HEATING = 3